# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true

reviews:
  profile: "assertive"
  # Key feature: automatically approves when conversations are resolved
  request_changes_workflow: true
  high_level_summary: true
  review_status: true

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

  path_filters:
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/.expo/**"

  path_instructions:
    # 1. Domain Architecture Rules
    - path: "packages/domain/src/**/*"
      instructions: |
        You are a Senior Software Architect. Strict enforcement required:
        - Layer Isolation: Zero dependencies on external frameworks or Appwrite SDK. No 'appwrite' imports here.
        - Dependency Direction: Dependencies must point inwards.
        - Repository Pattern: Persistence must be accessed through interfaces defined in this layer.
        - TDD: Every logic change must have a corresponding .spec.ts file.
        - Naming: Use ubiquitous language (e.g., 'Reservation' instead of 'Booking').

    # 2. App Rules (React Native + Expo)
    - path: "apps/**/*.{ts,tsx}"
      instructions: |
        Mobile Best Practices:
        - Accessibility: Touch targets min 44x44.
        - Performance: Use FlatList/SectionList for lists.
        - Styles: Use StyleSheet.create instead of inline styles.
        - Hooks: Validate memory leaks in useEffect.

    # 3. General TypeScript Rules
    - path: "**/*.{ts,tsx}"
      instructions: |
        - Avoid 'any', use explicit types.
        - Prefer 'import type' for type imports.
        - Documentation: Public methods/classes MUST have JSDoc describing purpose, params, and returns.
